### ISSUE TITLE
allow numerical operators in filters for numerical variables

### ISSUE THREAD

**Issue by mwvoss** [HBClab/intervention-outcomes#4]
It would be desirable to filter numerical variables like sample size using numerical operators. e.g., a filter to plot only studies with sample size >30

**Comment by zkhan12** [comment]
![image](https://user-images.githubusercontent.com/38085378/74486507-b2297d80-4e82-11ea-9060-919e35d01bac.png)

I resolved this issue using sliders instead of inequalities. So now if you click on a column filter text box, it should bring up a slider so the user can select a range. However, this does create a slightly annoying bug where the first time you select a filter box, it resets the position of the table on the page. I'll open a separate issue to fix this later on, but the main functionality should work as expected afterwards.
